apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv 
  labels:
    type: local
spec:
  capacity:
    storage: 15Gi
  local:
    path: /mnt/ollama-models
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - slave-srv2.local