apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama
  namespace: ollama
  labels:
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/name: ollama
automountServiceAccountToken: true
